---
- name: Instalar paquetes java del SO Debian
  apt: name={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items: '{{ java_packages_debian }}'
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Instalar paquetes java del SO CentOs
  yum: name={{ item }} state=latest
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  with_items: '{{ java_packages_centos }}'